# Generated by Django 4.2.7 on 2025-10-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_device_offline', models.BooleanField(default=True)),
                ('email_low_battery', models.BooleanField(default=True)),
                ('email_geofence_breach', models.BooleanField(default=True)),
                ('email_command_response', models.BooleanField(default=False)),
                ('sms_device_offline', models.BooleanField(default=True)),
                ('sms_low_battery', models.BooleanField(default=False)),
                ('sms_geofence_breach', models.BooleanField(default=True)),
                ('sms_command_response', models.BooleanField(default=False)),
                ('push_device_offline', models.BooleanField(default=True)),
                ('push_low_battery', models.BooleanField(default=True)),
                ('push_geofence_breach', models.BooleanField(default=True)),
                ('push_command_response', models.BooleanField(default=True)),
                ('offline_check_interval', models.IntegerField(default=30, help_text='Minutes between offline checks')),
                ('battery_warning_threshold', models.IntegerField(default=20, help_text='Battery percentage for low battery warning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('device_offline', 'Device Offline'), ('device_online', 'Device Online'), ('low_battery', 'Low Battery'), ('geofence_breach', 'Geofence Breach'), ('command_response', 'Command Response'), ('system_alert', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('animal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx')],
            },
        ),
    ]
