# Generated by Django 5.2.7 on 2025-10-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('donkey', 'Donkey'), ('pig', 'Pig'), ('sheep', 'Sheep'), ('goat', 'Goat')], default='cow', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
    ]
