# Generated by Django 5.2.7 on 2026-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_animal_category_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('buzzer', 'Activate Buzzer'), ('sms', 'Send SMS'), ('location', 'Request Location'), ('status', 'Request Status'), ('configuration', 'Configuration')], max_length=20),
        ),
    ]
